mysite/main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns('',
	url(r'^news/(?P<pk>\d+)$', views.about, name='about'),
	url(r'^news/', views.index, name='news'),
	url(r'^$', views.default, name='default'),
)

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.flatpages import views
import django.views.defaults


urlpatterns = [


    url(r'^', include('main.urls', namespace="main")),
    url(r'^speakers/', include('speakers.urls',  namespace="speakers")),
    url(r'^sponsors/', include('sponsors.urls', namespace="sponsors")),
    url(r'^performances/', include('performances.urls', namespace="performances")),
    url(r'^organizers/', include('organizers.urls', namespace="organizers")),
    url(r'^search/', include('search.urls')),
    url(r'^about-us/$', views.flatpage, {'url': '/about-us/'}, name='about'),
    url(r'^users/', include('users.urls')),
    url(r'^404/$', django.views.defaults.page_not_found),

        


    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

mysite/organizers/urls.py
from django.conf.urls import patterns, url
from organizers import views
urlpatterns = patterns('',
url(r'^$', views.index, name='organizers'),
url(r'^(?P<pk>\d+)$', views.about, name='about'),
)

mysite/performances/urls.py
from django.conf.urls import patterns, url

from performances import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='performances'),
	url(r'^(?P<p>\d+)$', views.about, name='about'),
)

mysite/search/urls.py
from django.conf.urls import patterns, url

from search import views

urlpatterns = patterns('',
	(r'^$', views.search),
)

mysite/speakers/urls.py
from django.conf.urls import patterns, url

from speakers import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<pk>\d+)$', views.about, name='about'),
)

mysite/sponsors/urls.py
from django.conf.urls import patterns, url
from sponsors import views

urlpatterns = patterns('',
url(r'^$', views.index, name='index'),
url(r'^new/sponsor/$', views.sponsor_new, name ="sponsor_new"),
url(r'^(?P<pk>\d+)/edit/$', views.sponsor_edit, name='sponsor_edit'),
url(r'^(?P<pk>\d+)/delete/$', views.sponsor_delete, name='delete'),
url(r'^(?P<pk>\d+)$', views.about, name='about'),
)

mysite/organizers/models.py
from django.db import models

class Organizer(models.Model):
	fio = models.CharField(max_length=70)
	description = models.TextField()
	comunications = models.TextField()
	photo = models.ImageField()
	
	def __unicode__(self):
	        return self.fio

	def __str__(self):
	        return self.fio

mysite/performances/models.py
from django.db import models

class Performance(models.Model):
	name = models.CharField(max_length=55)
	img = models.ImageField(null = True, blank = True)
	description = models.TextField()
	time = models.DateTimeField()
	pub_date = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['time']

	def __str__(self):
		return self.name

	def __unicode__(self):
		return self.name

mysite/search/models.py
from django.db import models

# Create your models here.

mysite/speakers/models.py
from django.db import models

class Speaker(models.Model):
	fio = models.CharField(max_length=70)
	description = models.TextField()
	photo = models.ImageField(upload_to="")
	
		
	def __unicode__(self):
		return self.fio

	def __str__(self):
		return self.fio

mysite/sponsors/models.py
from django.db import models

class Sponsor(models.Model):
	name = models.CharField(max_length=255)
	description = models.TextField(max_length=255)
	logo = models.ImageField(null = True, blank = True)
	
			
	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name
	

mysite/sponsors/forms.py
from django import forms
from .models import Sponsor

class SponsorForm(forms.ModelForm):

	class Meta:
		model = Sponsor
		fields = ('name','description','logo')

mysite/organizers/views.py
from django.shortcuts import render,get_object_or_404
import datetime
from performances.models import Performance
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



from .models import Organizer


def index(request):
	news_list = Organizer.objects.all()

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)

	paginator = Paginator(news_list, 6)
	page = request.GET.get('page')
	try:
		contacts = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		contacts = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		contacts = paginator.page(paginator.num_pages)

	context = {'organizers': contacts,'now':now, 'perf':perf[:5]}
	return render(request, 'organizers.html', context)
# Create your views here.

def about(request,pk):
	organizer = get_object_or_404(Organizer, pk = pk)

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	context = {'organizer':organizer,'now':now, 'perf':perf[:5]}
	return render(request, 'about_organizer.html', context)

mysite/performances/views.py
from django.shortcuts import render,get_object_or_404
import datetime
from .models import Performance
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
	performances_list = Performance.objects.all()

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	paginator = Paginator(performances_list, 5)
	page = request.GET.get('page')
	try:
		contacts = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		contacts = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		contacts = paginator.page(paginator.num_pages)
	context = {'performances': contacts,'now':now, 'perf':perf[:5]}
	return render(request, 'performances.html', context)


def about(request, p):
	performance = get_object_or_404(Performance, pk = p)

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	context = {'performance':performance,'now':now, 'perf':perf[:5]}
	return render(request, 'about_performance.html', context)

mysite/search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from speakers.models import Speaker
from organizers.models import Organizer
from sponsors.models import Sponsor
from performances.models import Performance
from main.models import Main
import datetime

# Create your views here.


def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']

        now = datetime.datetime.now()
        perf = Performance.objects.filter(time__gt = now)
        
        news = Main.objects.filter(title__icontains=q)            
        speakers = Speaker.objects.filter(fio__icontains=q)
        organizers = Organizer.objects.filter(fio__icontains=q) 
        sponsors = Sponsor.objects.filter(name__icontains=q) 
        performances = Performance.objects.filter(name__icontains=q)

        return render(request,'search.html',
            {'speakers': speakers,
            'organizers':organizers,
            'sponsors':sponsors,
            'performances':performances,
            'news':news,

            'now':now,
            'perf':perf[:5],

            'query': q})
    else:
        return HttpResponse('Please submit a search term.')

mysite/speakers/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Speaker
import datetime
from performances.models import Performance

def index(request):
	speakers_list = Speaker.objects.all()

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	paginator = Paginator(speakers_list, 6)
	page = request.GET.get('page')
	try:
		contacts = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		contacts = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		contacts = paginator.page(paginator.num_pages)
	context = {'speaker':contacts,'now':now, 'perf':perf[:5]}
	return render(request, 'speakers.html', context)

def about(request, pk):
	speaker = get_object_or_404(Speaker, pk = pk)

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	context = {'speaker':speaker,'now':now, 'perf':perf[:5]}
	return render(request, 'about_speaker.html', context)

mysite/sponsors/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from .forms import SponsorForm
from .models import Sponsor
import datetime
from performances.models import Performance
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def index(request):
	sponsors_list = Sponsor.objects.all()

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)

	paginator = Paginator(sponsors_list, 5)
	page = request.GET.get('page')
	try:
		contacts = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		contacts = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		contacts = paginator.page(paginator.num_pages)
	context = {'Sponsor':contacts,'now':now, 'perf':perf[:5]}
	return render(request, 'sponsors.html', context) 

def sponsor_new(request):
	
	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	if request.method == "POST":
		form = SponsorForm(request.POST,request.FILES)


		if form.is_valid():
			Sponsor = form.save(commit ="False")
			Sponsor.save()	
			return redirect('sponsors:index')
	else:
		form = SponsorForm()
	return render(request,'sponsor_edit.html', {'form':form,'now':now, 'perf':perf[:5]})

def sponsor_edit(request, pk):
	sponsor = get_object_or_404(Sponsor, pk = pk)

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	if request.method == "POST":
		form = SponsorForm(request.POST,request.FILES, instance = sponsor)
		if form.is_valid():
			sponsor = form.save(commit = False)
			sponsor.save()
			return redirect('sponsors:index')
	else:
		form = SponsorForm(instance = sponsor)

	return render(request, "sponsor_edit.html",{"form":form,'now':now, 'perf':perf[:5]})

def sponsor_delete(request, pk):
	sponsor = get_object_or_404(Sponsor, pk = pk)
	sponsor.delete()
	return redirect('sponsors:index')


def about(request, pk):
	sponsor = get_object_or_404(Sponsor, pk = pk)

	now = datetime.datetime.now()
	perf = Performance.objects.filter(time__gt = now)
	
	context = {'sponsor':sponsor,'now':now, 'perf':perf[:5]}
	return render(request, 'about_sponsor.html', context)

mysite/templates/about_news.html
{% extends "base.html" %}

{% block head %}
{{news.title}}
{%endblock%}


{% block content %}	
<div class = "main">
<div class ="perf_pubdate"> {{ news.pub_date|date:"G:i j.n.Y " }}</div>
<div class="defn">{{news.description}}</div>
</div>
{% endblock %}

mysite/templates/about_organizer.html
{% extends "base.html" %}

{% block head %}
{{organizer.fio}}
{%endblock%}


{% block content %}	
<div class = "main">
<div class="about_image"><img src = "{{organizer.photo.url}}"></div>
<div class = "fio"> Some information about {{organizer.fio}}. </div>
<div class="defn">{{organizer.description}}</div>
<br>
<div clas = "fio">Contacts</div>
<div class ="defn">{{organizer.comunications}}</div>
</div>
{% endblock %}

mysite/templates/about_performance.html
{% extends "base.html" %}

{% block head %}
{{performance.name|capfirst}}
{%endblock%}


{% block content %}	
<div class = "main">
				<div class = "perf_pubdate"> {{ performance.pub_date|date:"G:i j.n.Y " }}</div>
				<div><font size="6">{{ performance.time|date:"G:i j M Y l" }}</font></div>
				
				<p>{{ performance.description|capfirst }}</p>
					
</div>
{% endblock %}

mysite/templates/about_speaker.html
{% extends "base.html" %}

{% block head %}
{{speaker.fio}}
{%endblock%}


{% block content %}	
<div class = "main">
<div class="about_image"><img src = "{{speaker.photo.url}}"></div>
<div class = "fio"> Some information about {{speaker.fio}}. </div>
<div class="defn">{{speaker.description}}</div>
</div>
{% endblock %}

mysite/templates/about_sponsor.html
{% extends "base.html" %}

{% block head %}
{{sponsor.name}}
{%endblock%}


{% block content %}	
<div class = "main">
<div class="about_image"><img src = "{{sponsor.logo.url}}"></div>
<div class = "fio"> Information about {{sponsor.name}}. </div>
<div class="defn">{{sponsor.description}}</div>
</div>
{% endblock %}

mysite/templates/base.html
<html>
{% load staticfiles %}
	<head>
		<link rel= "stylesheet" href="{% static "style.css" %}">
		<meta charset="utf-8">
		<title>Conference</title>
	</head>

	<body>
		
		<div class ="allr">
		<div class="fixed">
			
			<form action="/search/" method="get">
		        <input type="text" name="q" placeholder="What you find?">
		        <input id = "search" type="submit" value="Search" >
		    </form>
			<br>
				Time: {{ now|date:" j M Y G:i" }}
			<br>
			
			<br>
			{%if request.user.username %}
				<div>Hello, {{request.user.username}}!</div><a href= "/users/logout/">logout</a>
				<br>

				{% if request.user.is_superuser %}
				<br>
				  <a href="/admin/">admin interface</a>
				  <br>
				{% endif %}

			{%else%}
			
				<form action="/users/base_login/" method="post">{% csrf_token %}
		        <input type="text" name="username" placeholder="username">
		        <input type="password" name="password" placeholder="password">
		       <br>
				<input type="submit" value = "Login">
				<input type = "submit" formaction = "/users/register/" value="Registration">
				</form>

			{%endif%}
			<br>
			{% if perf %}
				<div class = "text"> <font size = "5pt">Upcoming performances</font></div>
				<ul>

				{% for p in perf %}
					<li>{{p|capfirst}}<br>{{p.time|date:" j M Y G:i"}}</li>
						
				{% endfor %}
				</ul>
			{% else %}

				<div class = "text"> <font size = "5pt">Not upcoming performances</font></div>

			{% endif %}

		</div>
		</div>
			<div class="fixed" id="menu">
				<div class="menu">
					<a href="{% url 'main:default'%}"> Home page </a>
				</div>
				<div class="menu">
					<a href="{% url 'main:news'%}"> News </a>
				</div>
				<div class="menu">
					<a href="{% url 'speakers:index' %}"> Speakers </a>
				</div>
				<div class="menu">
					<a href="{% url 'performances:performances' %}"> Performances </a>
				</div>
				<div class="menu">
					<a href="{% url 'organizers:organizers' %}"> Organizers </a>
				</div>
				<div class="menu">
					<a href="{% url 'sponsors:index'%}"> Sponsors </a>
				</div>
			</div>
		<div class = "all">			
<div class="fix"></div>
<br><br>
				<div align="center" style = "font-family:calibri; color:gray; font-size:70px">
					{% block head %}{% endblock %}
				</div>

				{% block content%}
				{%endblock%}

		</div>



	</body>
</html>

mysite/templates/index.html
{% extends "base.html" %}

{% block head %}
Scientific conference
{%endblock%}	
{% block content %}


<div class = "main">
<p>
Information
</p>
</div>
{% endblock %}

mysite/templates/main_page.html
{% extends "base.html" %}

{% block head %}
News
{%endblock%}	
{% block content %}
<br>

{% for main_item in main %}

<div class = "main">
<div class ="perf_pubdate"> {{ main_item.pub_date|date:"G:i j.n.Y " }}</div>
<center>
    <h2 class = "text">{{main_item.title|upper}}</h5>
    <span class = "text">{{ main_item.description|capfirst }}</span>
    <a class="more" href= "{% url 'main:about' pk=main_item.id %}">more</a>
</center>
</div>


{% endfor %}

		<div class="pagination">
            <span class="step-links" style="display: inline-block; margin-bottom: 20px">
            {% if main.has_previous %}
                <a href="?page={{ main.previous_page_number }}" style="display: inline-block;padding-left: 0">previous</a>
            {% endif %}

            <span class="current" style="display: inline-block">
                Page {{ main.number }} of {{ main.paginator.num_pages }}.
            </span>

            {% if main.has_next %}
                <a href="?page={{ main.next_page_number }}" style="display: inline-block">next</a>
            {% endif %}
            </span>
        </div>
{% endblock %}

mysite/templates/performances.html
{% extends "base.html" %}

{% block head %}
Perfomances
{%endblock%}
		{% block content %}
		{% for performances_item in performances %}
			<div class="perfomance">
			
				<div class = "perfomance_left">
					<div class = "perfomance_img">
					{% if performances_item.img %}
						<img src="{{performances_item.img.url}}" alt ="картинка">
					{% endif %}
					</div>
					<p></p>
					<div class = "perfomance_time">{{ performances_item.time|date:"G:i j M Y l" }}</div>
				</div>
				<div class = "perfomance_desc fio">{{ performances_item.name|upper }}</div>
				<div class = "perf_pubdate"> {{ performances_item.pub_date|date:"G:i j.n.Y " }}</div>
		
				<br><br><br>
				<div class = "perfomance_desc">{{ performances_item.description|truncatechars:550|capfirst }}</div>
					
				<a class="more" href = "{% url 'performances:about' p=performances_item.id  %}">more</a>
				
			</div>
			
		{% endfor %}


		<div class="pagination">
            <span class="step-links" style="display: inline-block; margin-bottom: 20px">
            {% if performances.has_previous %}
                <a href="?page={{ performances.previous_page_number }}" style="display: inline-block;padding-left: 0">previous</a>
            {% endif %}

            <span class="current" style="display: inline-block">
                Page {{ performances.number }} of {{ performances.paginator.num_pages }}.
            </span>

            {% if performances.has_next %}
                <a href="?page={{ performances.next_page_number }}" style="display: inline-block">next</a>
            {% endif %}
            </span>
        </div>
		{% endblock %}

mysite/templates/register.html
{% extends "base.html" %}

{% block head %}
Regisration
{%endblock%}  
{% block content %}
Write your username and invent passowrd
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Register</button>
    </form>
{% endblock %}

mysite/templates/search.html
{% extends "base.html" %}

{% block head %}
Search
{% endblock %}	
		{% block content %}
			<p>You searched for: <strong>{{ query }}</strong></p>
			{%if speakers or organizers or sponsors or performances  %}		

				{% if news %}
				    <p>Found news: {{ news|length }} object </p>
				    <ul>
				        {% for book in news %}
				        <li><a href ="{% url 'main:about' pk=book.id %}">{{ book.title }}</a></li>
				        {% endfor %}
				    </ul>
				{%endif%}

				{% if speakers %}
				    <p>Found speakers: {{ speakers|length }} object </p>
				    <ul>
				        {% for book in speakers %}
				        <li><a href ="{% url 'speakers:about' pk=book.id %}">{{ book.fio }}</a></li>
				        {% endfor %}
				    </ul>
				{%endif%}

				{% if performances %}
					<p>Found performances: {{ performances|length }} object </p>
				    <ul>
				        {% for book in performances %}
				        <li><a href ="{% url 'performances:about' p=book.id %}">{{ book.name }}</a></li>
				        {% endfor %}
				    </ul>
				{% endif %}

				{% if organizers %}
					<p>Found organizers: {{ organizers|length }} object </p>
				    <ul>
				        {% for book in organizers %}
				        <li><a href ="{% url 'organizers:about' pk=book.id %}">{{ book.fio }}</a></li>
				        {% endfor %}
				    </ul>
				{% endif %}

				{% if sponsors %}
					<p>Found sponsors: {{ sponsors|length }} object </p>
				    <ul>
				        {% for book in sponsors %}
				        <li><a href ="{% url 'sponsors:about' pk=book.id %}">{{ book.name }}</a></li>
				        {% endfor %}
				    </ul>
				{% endif %}



			{% else %}
			    <p>No results matched your search criteria.</p>
			{% endif %}
		{% endblock %}

mysite/templates/speakers.html
{% extends "base.html" %}

{% block head %}
Speakers
{%endblock%}

		{% block content %}
		{% for speakers_item in speaker %}

			<div class="speaker">
				<div class = "image" style ="background: url({{speakers_item.photo.url}}) no-repeat center center;background-size:cover;">
				</div>
				<div class = "fio">{{ speakers_item.fio|title}}</div>
				<div class = "defn">{{ speakers_item.description|truncatechars:160|capfirst }}</div>
				<a class="more" href= "{% url 'speakers:about' pk=speakers_item.id %}">more</a>
			</div>
	
		{% endfor %}
		<div class="fix"></div>
		    <div class="pagination">
            <span class="step-links" style="display: inline-block; margin-bottom: 20px">
            {% if speaker.has_previous %}
                <a href="?page={{ speaker.previous_page_number }}" style="display: inline-block;padding-left: 0">previous</a>
            {% endif %}

            <span class="current" style="display: inline-block">
                Page {{ speaker.number }} of {{ speaker.paginator.num_pages }}.
            </span>

            {% if speaker.has_next %}
                <a href="?page={{ speaker.next_page_number }}" style="display: inline-block">next</a>
            {% endif %}
            </span>
        </div>
		{% endblock %}

	

mysite/templates/sponsor_edit.html
{%extends 'base.html'%}
{% block content %}
<h1>Sponsor edit </h1>
<form enctype="multipart/form-data" method = "POST" class ="post-form">{% csrf_token %}

{{ form.as_p }}

<button type = "submit">Save</button>
</form>
{% endblock %}

mysite/templates/sponsors.html
{% extends "base.html" %}

{% block head %}
Sponsors
{%endblock%}

		{% block content %}	
		{% if request.user.is_superuser %}
					  <a href="{% url 'sponsors:sponsor_new' %}"><span class = "text">create new sponsor</span></a>
					  <br><br>
		{% endif %}
		{% for sponsor in Sponsor %}
	
			<div class="perfomance">
				<div class = "perfomance_left">
					<div class = "perfomance_img" id ="sponsor">
					{% if sponsor.logo %}
						<img src = "{{sponsor.logo.url }}">
					{% endif %}
					</div>
					<br>
					{% if request.user.is_superuser %}
						<button><a class ="redirect" href="{% url 'sponsors:sponsor_edit' pk=sponsor.id %}">Redirect</a></button>
						 <button><a href="{% url 'sponsors:delete' sponsor.id %}">Delete</a></button>
					{%endif%}
				</div>
				<div class = "perfomance_desc fio"> {{ sponsor.name|upper }}</div> 
								<br><br><br>
				<div class = "perfomance_desc">{{ sponsor.description|truncatechars:550|capfirst  }}</div>

				<a class="more" href= "{% url 'sponsors:about' pk=sponsor.id %}">more</a>
    
    			

				<div class="fix"></div>
			</div>
			
		{% endfor %}

		    <div class="pagination">
            <span class="step-links" style="display: inline-block; margin-bottom: 20px">
            {% if Sponsor.has_previous %}
                <a href="?page={{ Sponsor.previous_page_number }}" style="display: inline-block;padding-left: 0">previous</a>
            {% endif %}

            <span class="current" style="display: inline-block">
                Page {{ Sponsor.number }} of {{ Sponsor.paginator.num_pages }}.
            </span>

            {% if Sponsor.has_next %}
                <a href="?page={{ Sponsor.next_page_number }}" style="display: inline-block">next</a>
            {% endif %}
            </span>
        </div>
		{% endblock %}